# Deployment config for Vercel (Frontend)
name: Deploy Frontend to Vercel
on:
  push:
    branches: [main]
    paths: ['client/**']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install -g vercel
      - name: Deploy
        run: |
          cd client
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
